hmrc/alcohol-duty-ui-tests

src/test/resources/features/alcoholToDeclare/AlcoholDutyReturns.feature, src/test/resources/features/alcoholToDeclare/AlcoholDutyReturnsErrorMessages.feature, src/test/resources/features/dutySuspendedDeliveries/DutySuspendedDeliveries.feature, src/test/resources/features/dutySuspendedDeliveries/DutySuspendedDeliveriesErrorMessages.feature, src/test/scala/uk/gov/hmrc/alcoholDuty/cucumber/stepdefs/BaseStepDef.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/alcoholDuty/alcoholToDeclare/AlcoholByVolumePage.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/alcoholDuty/alcoholToDeclare/DraughtReliefPage.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/alcoholDuty/alcoholToDeclare/ProductNamePage.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/alcoholDuty/alcoholToDeclare/ProductVolumePage.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/alcoholDuty/alcoholToDeclare/SmallReliefProducerPage.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/alcoholDuty/dutySuspendedDeliveries/DeclareDutySuspendedDeliveriesOutsideUKPage.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/alcoholDuty/dutySuspendedDeliveries/DeclareDutySuspendedDeliveriesPage.scala
..also small code refactor to mange the features as per the journey type
=> ADR-796: Declare Duty Suspended Deliveries Outside UK Page feature implemented

src/test/resources/features/alcoholToDeclare/AlcoholDutyReturns.feature, src/test/resources/features/alcoholToDeclare/AlcoholDutyReturnsErrorMessages.feature, src/test/resources/features/dutySuspendedDeliveries/DutySuspendedDeliveries.feature, src/test/resources/features/dutySuspendedDeliveries/DutySuspendedDeliveriesErrorMessages.feature, src/test/scala/uk/gov/hmrc/alcoholDuty/cucumber/stepdefs/BaseStepDef.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/BasePage.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/alcoholDuty/dutySuspendedDeliveries/DutySuspendedDeliveriesGuidancePage.scala
Added Acceptance Tests for Guidance page
=> ADR-795 Tests added for the guidance page

src/test/resources/features/quarterlySpiritsQuestions/QuarterlySpiritsQuestions.feature, src/test/resources/features/quarterlySpiritsQuestions/QuarterlySpiritsQuestionsErrorMessages.feature, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/alcoholDuty/quarterlySpiritsQuestion/DeclareIrishWhiskeyPage.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/alcoholDuty/quarterlySpiritsQuestion/DeclareIrishWhiskyPage.scala
Updated Automation tests for Irish Whiskey page
=> ADR 830: Updated Automation tests for Irish Whiskey page

README.md, loggerUtils.sh, run_a11y_local.sh
=> ADR 841: Updated Readme

src/test/resources/features/quarterlySpiritsQuestions/QuarterlySpiritsQuestions.feature, src/test/resources/features/quarterlySpiritsQuestions/QuarterlySpiritsQuestionsErrorMessages.feature, src/test/scala/uk/gov/hmrc/alcoholDuty/cucumber/stepdefs/BaseStepDef.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/alcoholDuty/quarterlySpiritsQuestion/HowMuchWheatHaveYouUsedPage.scala
Added automation tests for wheat screen
=> ADR-847 Added automation tests for wheat screen

src/test/resources/features/alcoholToDeclare/AlcoholDutyReturns.feature
Included £ in front of Duty Due Per Litre
=> ADR-883 Included £ in front of Duty Due Per Litre

build.sbt, project/Dependencies.scala, project/plugins.sbt, run_accessibility_tests.sh, run_browser_with_docker.sh, run_dockerised_tests.sh, run_tests.sh, run_zap_tests.sh, src/test/scala/uk/gov/hmrc/alcoholDuty/cucumber/stepdefs/BaseStepDef.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/cucumber/stepdefs/Hooks.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/driver/BrowserDriver.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/BasePage.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/alcoholDuty/alcoholToDeclare/TaxTypePage.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/alcoholDuty/quarterlySpiritsQuestion/WhichOfTheseSpiritsHaveYouMadePage.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/generic/PageObjectFinder.scala, startup_auth.sh
I ran the UI tests from the branch with new configurations and all worked as expected.
https://build.tax.service.gov.uk/job/Alcohol%20Duty/job/Alcohol%20Duty%20UI%20Tests/70/cucumber-html-reports/overview-features.html
=> ADR-864: UI migration code is implemented as per the instructions

src/test/resources/features/alcoholToDeclare/AlcoholDutyReturns.feature
Small update to verify the product list after deleting product
=> ADR-832 Small update to delete product test

src/test/scala/uk/gov/hmrc/alcoholDuty/pages/alcoholDuty/adjustments/AdjustmentAlcoholByVolumePage.scala
=> ADR-927 Removed unused imports

src/test/resources/features/dutySuspendedDeliveriesJourney/DutySuspendedDeliveries.feature, src/test/resources/features/dutySuspendedDeliveriesJourney/DutySuspendedDeliveriesErrorMessages.feature, src/test/scala/uk/gov/hmrc/alcoholDuty/cucumber/stepdefs/BaseStepDef.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/BasePage.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/alcoholDuty/dutySuspendedDeliveries/DutySuspendedBeerPage.scala
UI tests added for Duty Suspended Beer Page
=> ADR-961 UI tests added for Duty Suspended Beer Page

src/test/resources/features/dutySuspendedDeliveriesJourney/DutySuspendedDeliveries.feature, src/test/resources/features/dutySuspendedDeliveriesJourney/DutySuspendedDeliveriesErrorMessages.feature, src/test/scala/uk/gov/hmrc/alcoholDuty/cucumber/stepdefs/BaseStepDef.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/alcoholDuty/dutySuspendedDeliveries/DutySuspendedSpiritsPage.scala
UI tests added for Duty Suspended Spirits Page
=> ADR-968 UI tests added for Duty Suspended Spirits Page

src/test/resources/features/dutySuspendedDeliveriesJourney/DutySuspendedDeliveries.feature, src/test/resources/features/dutySuspendedDeliveriesJourney/DutySuspendedDeliveriesErrorMessages.feature, src/test/scala/uk/gov/hmrc/alcoholDuty/cucumber/stepdefs/BaseStepDef.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/alcoholDuty/dutySuspendedDeliveries/DutySuspendedDeliveriesCheckYourAnswersPage.scala
UI Tests Added for DSD Check Your Answers Page
=> ADR-972 UI Tests Added for DSD Check Your Answers Page

src/test/resources/features/quarterlySpiritsQuestionsJourney/QuarterlySpiritsQuestions.feature, src/test/resources/features/quarterlySpiritsQuestionsJourney/QuarterlySpiritsQuestionsErrorMessages.feature, src/test/scala/uk/gov/hmrc/alcoholDuty/cucumber/stepdefs/BaseStepDef.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/alcoholDuty/quarterlySpiritsQuestion/DeclareOtherMaltedGrainsPage.scala
UI Tests added for Other Malted Grains Page
=> ADR 1030 UI Tests added for Other Malted Grains Page

src/test/resources/features/quarterlySpiritsQuestionsJourney/QuarterlySpiritsQuestions.feature, src/test/resources/features/quarterlySpiritsQuestionsJourney/QuarterlySpiritsQuestionsErrorMessages.feature, src/test/scala/uk/gov/hmrc/alcoholDuty/cucumber/stepdefs/BaseStepDef.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/alcoholDuty/quarterlySpiritsQuestion/DeclareOtherSpiritsProducedPage.scala
Updated UI Tests for Other Spirits Produced Screen
=> ADR-999 Updated UI Tests for Other Spirits Produced Screen

src/test/resources/features/quarterlySpiritsQuestionsJourney/QuarterlySpiritsQuestions.feature
=> ADR-1037 Fixed failed test

src/test/resources/features/adjustmentsJourney/AdjustmentsJourneyErrorMessages.feature, src/test/resources/features/adjustmentsJourney/AdjustmentsJourneyHappyPath.feature, src/test/resources/features/alcoholToDeclareJourney/AlcoholDutyReturns.feature, src/test/resources/features/alcoholToDeclareJourney/AlcoholDutyReturnsChangeLinksCYAPage.feature, src/test/resources/features/alcoholToDeclareJourney/AlcoholDutyReturnsErrorMessages.feature, src/test/resources/features/commonPageFeatures/TaskListPage.feature, src/test/resources/features/dutySuspendedDeliveriesJourney/DutySuspendedDeliveries.feature, src/test/resources/features/dutySuspendedDeliveriesJourney/DutySuspendedDeliveriesErrorMessages.feature, src/test/resources/features/quarterlySpiritsQuestionsJourney/QuarterlySpiritsQuestions.feature, src/test/resources/features/quarterlySpiritsQuestionsJourney/QuarterlySpiritsQuestionsChangeLinksCYAPage.feature, src/test/resources/features/quarterlySpiritsQuestionsJourney/QuarterlySpiritsQuestionsErrorMessages.feature, src/test/scala/uk/gov/hmrc/alcoholDuty/cucumber/stepdefs/AlcoholDutyStepDef.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/auth/AuthLoginStubPage.scala
Updated UI Tests with Affinity Type
=> ADR-786: Updated UI Tests with Affinity Type

src/test/resources/features/commonPageFeatures/NoAppaId.feature, src/test/scala/uk/gov/hmrc/alcoholDuty/cucumber/stepdefs/AlcoholDutyStepDef.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/common/NoApprovalIdPage.scala
UI test added for No approval Id page
=> ADR: 1097 UI test added for No approval Id page

src/test/resources/features/commonPageFeatures/ViewPastReturnsPage.feature, src/test/scala/uk/gov/hmrc/alcoholDuty/cucumber/runner/Runner.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/cucumber/stepdefs/BaseStepDef.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/BasePage.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/common/ViewSpecificReturnPage.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/generic/PageObjectFinder.scala
UI Tests added for View Specific Returns
=> ADR-1080 UI Tests added for View Specific Returns

src/test/resources/features/adjustmentsJourney/AdjustmentsJourneyChangeLinksCYAPage.feature, src/test/resources/features/adjustmentsJourney/AdjustmentsJourneyErrorMessages.feature, src/test/resources/features/adjustmentsJourney/AdjustmentsJourneyHappyPath.feature, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/alcoholDuty/adjustments/AdjustmentCheckYourAnswersPage.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/alcoholDuty/adjustments/OverDeclarationReasonPage.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/alcoholDuty/adjustments/UnderDeclarationReasonPage.scala
UI tests updated for under-declaration and over-declaration reason page
=> ADR-1253: UI tests updated for under-declaration and over-declaration reason page

src/test/resources/features/dutySuspendedDeliveriesJourney/DutySuspendedDeliveries.feature
Updated UI tests after bug fix
=> ADR-1272: Updated UI tests after bug fix

src/test/resources/features/adjustmentsJourney/AdjustmentsJourneyChangeLinksCYAPage.feature, src/test/resources/features/adjustmentsJourney/AdjustmentsJourneyHappyPath.feature
Updated Adjustment journey feature file tags and tests
=> ADR-1272: Updated Adjustment journey feature file tags and tests

src/test/resources/features/commonPageFeatures/TaskListPage.feature, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/alcoholDuty/adjustments/AdjustmentListPage.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/common/ReturnSummaryPage.scala
Fixed Adjustment list page url and failing test
=> ADR-861: Fixed Adjustment list page url and failing test

src/test/resources/features/commonPageFeatures/ViewPastReturnsPage.feature, src/test/scala/uk/gov/hmrc/alcoholDuty/cucumber/stepdefs/BaseStepDef.scala
Added UI test for No Outstanding Returns scenario
=> ADR-1221: Added UI test for No Outstanding Returns scenario

src/test/resources/features/alcoholToDeclareJourney/AlcoholDutyReturnFullJourney.feature, src/test/resources/features/alcoholToDeclareJourney/AlcoholDutyReturnsChangeLinksCYAPage.feature, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/BasePage.scala
Updated Adjustment journey test with replaced new hidden text
Updated returns journey tests to remove hidden text from feature files
=> ADR-1265: Updated Adjustment journey test with replaced new hidden text

project/Dependencies.scala, run_allTests.sh, run_tests.sh, src/test/resources/features/commonPageFeatures/BusinessAccountRedirection.feature, src/test/resources/features/commonPageFeatures/ClaimEnrolmentJourney.feature
Updated ui-test-runner and changed browser to chrome
=> ADR-928: Updated ui-test-runner and changed browser to chrome

src/test/resources/features/quarterlySpiritsQuestionsJourney/QuarterlySpiritsQuestionsChangeLinksCYAPage.feature, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/BasePage.scala
=> ADR-1357: Updated the period keys

src/test/resources/features/commonPageFeatures/ViewPastReturnsPage.feature, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/common/NilReturnSummaryPage.scala
ADR-1466: Values updated with not applicable text
=> ADR-1494: Page header updated for nil return

src/test/resources/features/adjustmentsJourney/AdjustmentsJourneyErrorMessages.feature, src/test/resources/features/dutySuspendedDeliveriesJourney/DutySuspendedDeliveriesErrorMessages.feature
Updated UI tests with new error messages
=> ADR-1442: Updated UI tests with new error messages

src/test/resources/features/adjustmentsJourney/AdjustmentsJourneyChangeLinksCYAPage.feature, src/test/resources/features/adjustmentsJourney/AdjustmentsJourneyErrorMessages.feature, src/test/resources/features/adjustmentsJourney/AdjustmentsJourneyHappyPath.feature, src/test/resources/features/alcoholToDeclareJourney/AlcoholDutyReturnFullJourney.feature, src/test/resources/features/alcoholToDeclareJourney/AlcoholDutyReturnFullJourneyWithLimitedRegimeApprovals.feature, src/test/resources/features/alcoholToDeclareJourney/AlcoholDutyReturnsChangeLinksCYAPage.feature, src/test/resources/features/alcoholToDeclareJourney/AlcoholDutyReturnsErrorMessages.feature, src/test/resources/features/commonPageFeatures/TaskListPage.feature, src/test/resources/features/quarterlySpiritsQuestionsJourney/QuarterlySpiritsQuestionsChangeLinksCYAPage.feature, src/test/resources/features/quarterlySpiritsQuestionsJourney/QuarterlySpiritsQuestionsErrorMessages.feature, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/BasePage.scala
Updated UI tests with tasklist content changes for different statuses
=> ADR-1436: Updated UI tests with tasklist content changes for different statuses

src/test/resources/features/adjustmentsJourney/AdjustmentsJourneyHappyPath.feature, src/test/resources/features/alcoholToDeclareJourney/AlcoholDutyReturnFullJourneyWithLimitedRegimeApprovals.feature
=> ADR-1597 Updated UI test Data for Switch on OFP feature toggle.

src/test/scala/uk/gov/hmrc/alcoholDuty/pages/BasePage.scala
=> Added new changes to quaterly Spirits Journey

src/test/resources/features/adjustmentsJourney/AdjustmentsJourneyErrorMessages.feature
=> Error message validation for Spoilt Beer Alcoholic Type

src/test/resources/features/alcoholToDeclareJourney/AlcoholDutyReturnsErrorMessages.feature
Added error messages to Alcohol duty Returns journey. No Change in code, Only front end error messages has been changed. All UI Tests has passed.
https://jira.tools.tax.service.gov.uk/browse/ADR-1803
=> Added Error messages to Alcohol duty Return Journey - ADR-1803

src/test/resources/features/commonPageFeatures/ViewPastPaymentsPage.feature
=> ADR-1735 Duty Uprate Updates and View Past Payments Script Updated

src/test/scala/uk/gov/hmrc/alcoholDuty/pages/alcoholDuty/alcoholToDeclare/OtherFermentedProducts/MultipleSmallProducerReliefRateOtherFermentedProductPage.scala, src/test/scala/uk/gov/hmrc/alcoholDuty/pages/alcoholDuty/alcoholToDeclare/Spirits/MultipleSmallProducerReliefRateSpiritsPage.scala
=> ADR-1877 - Updated Title, header and Error messages for Spirits and OFP on Multiple SPR Pages
